export enum CriteriaType {
  HOME_RUNS = 'HOME_RUNS',
  SWINGS = 'SWINGS',
  GAMES_PLAYED = 'GAMES_PLAYED',
  GUIDED_SESSIONS = 'GUIDED_SESSIONS',
  OPEN_SESSIONS = 'OPEN_SESSIONS',
  CONSECUTIVE_DAYS = 'CONSECUTIVE_DAYS',
  CONSECUTIVE_WEEKS = 'CONSECUTIVE_WEEKS',
  UPDATE_AVATAR = 'UPDATE_AVATAR',
  TOTAL_DISTANCE = 'TOTAL_DISTANCE',
  PERSONAL_BEST = 'PERSONAL_BEST',
  THROWS = 'THROWS',
  LEVEL_STATUS = 'LEVEL_STATUS'
}
