export enum DisplayChart {
  HISTOGRAM = 'HISTOGRAM',
  ATTACK_ANGLE = 'ATTACK_ANGLE',
  VERTICAL_BAT_ANGLE = 'VERTICAL_BAT_ANGLE',
  RADIAL = 'RADIAL',
  SPIN_EFFICIENCY = 'SPIN_EFFICIENCY',
  RELEASE_VELOCITY = 'RELEASE_VELOCITY'
}
