export enum EngineType {
  BARREL_SPEED_CLIMBER = 'BARREL_SPEED_CLIMBER',
  TRIGGER_TO_IMPACT = 'TRIGGER_TO_IMPACT',
  HOME_RUN_DERBY_BURNOUT = 'HOME_RUN_DERBY_BURNOUT',
  OPEN_SESSION = 'OPEN_SESSION',
  GUIDED_SESSION = 'GUIDED_SESSION',
  MINI_GAME = 'MINI_GAME',
  API_DRIVEN = 'API_DRIVEN',
  WEB_VIEW = 'WEB_VIEW'
}
