version: 0.2

phases:
  install:
    commands:
      - echo Updating everything...
      - apt-get update -y && apt-get upgrade -y
      - echo Installing AWS CLI tools...
      - apt-get install -y awscli
      - echo Installing package.json dependencies...
      - npm install
  pre_build:
    commands:
      - echo Configuring AWS CLI
      - aws configure set aws_access_key_id $ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
      - aws configure set default.region $DEFAULT_REGION
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - CURRENT_VERSION=$(npm show -q @diamondkinetics/dk-public-dto-ts version)
      - SRC_VERSION=$(node -pe "require('./package.json').version")
      - echo "//registry.npmjs.org/:_authToken=$npmToken" > ~/.npmrc
      - if [ "$CURRENT_VERSION" != "$SRC_VERSION" ]; then npm publish --access=public --dry-run=true; fi
      - if [ "$CURRENT_VERSION" = "$SRC_VERSION "]; then echo "No new version to publish (Currently $CURRENT_VERSION)."; fi
artifacts:
  files:
    - build/**/*
