import { AccountStatus } from './../enum/account-status';
import { BattingOrientation } from './../enum/batting-orientation';
import { DKSubscription } from './../enum/dk-subscription';
import { PlayType } from './../enum/play-type';
import { Position } from './../enum/position';
import { UserAppVersionOverrideDTOV2 } from './../v2/user-app-version-override.dto.v2';
import { AbstractSyncableDTOV3 } from './abstract-syncable.dto.v3';

export interface UserProfileDTOV3 extends AbstractSyncableDTOV3 {
	primaryEmail?: string;
	nickname?: string;
	firstName: string;
	lastName: string;
	secondaryEmail?: string;
	preferences?: string;
	claimSwingPlaneMetrics?: boolean;
	bouncing?: boolean;
	secondaryBouncing?: boolean;
	birthDate?: string;
	height?: string;
	weight?: string;
	playType: PlayType;
	battingOrientation?: BattingOrientation;
	throwsHandedness?: BattingOrientation;
	competitionLevelUuid?: string;
	coach?: boolean;
	hideFromSearch?: boolean;
	zipCode?: string;
	profileImageUrl?: string;
	userMetaData?: string;
	youthRegistration?: boolean;
	trialing?: boolean;
	activeMembership?: boolean;
	accountStatus?: AccountStatus;
	renewalDate?: string;
	appleRenewalDate?: string;
	subscribed?: boolean;
	subscribedTo?: DKSubscription;
	hadApplePaymentApplied?: boolean;
	referringOrganizationUuid?: string;
	pitchingAccountStatus?: AccountStatus;
	pitchingRenewalDate?: string;
	pitchingAppleRenewalDate?: string;
	pitchingHadApplePaymentApplied?: boolean;
	pitchingTrialing?: boolean;
	pitchingActiveMembership?: boolean;
	pitchingSubscribed?: boolean;
	pitchingSubscribedTo?: DKSubscription;
	axonBaseballId?: string;
	axonSoftballId?: string;
	paidViaLicense?: boolean;
	licenseOwner?: boolean;
	paidLicensesForCurrentBillingCycle?: number;
	appVersionOverrides?: UserAppVersionOverrideDTOV2[];
	state?: string;
	graduationYear?: string;
	position?: Position;
}
