import { UserAppVersionOverrideDTOV2 } from './../v2/user-app-version-override.dto.v2';
import { AbstractSyncableDTOV3 } from './abstract-syncable.dto.v3';

export interface UserProfileDTOV3 extends AbstractSyncableDTOV3 {
	primaryEmail?: string;
	nickname?: string;
	firstName: string;
	lastName: string;
	secondaryEmail?: string;
	preferences?: string;
	claimSwingPlaneMetrics?: boolean;
	bouncing?: boolean;
	secondaryBouncing?: boolean;
	birthDate?: string;
	height?: string;
	weight?: string;
	playType: string;
	battingOrientation?: string;
	throwsHandedness?: string;
	competitionLevelUuid?: string;
	coach?: boolean;
	hideFromSearch?: boolean;
	zipCode?: string;
	profileImageUrl?: string;
	userMetaData?: string;
	youthRegistration?: boolean;
	trialing?: boolean;
	activeMembership?: boolean;
	accountStatus?: string;
	renewalDate?: string;
	appleRenewalDate?: string;
	subscribed?: boolean;
	subscribedTo?: string;
	hadApplePaymentApplied?: boolean;
	referringOrganizationUuid?: string;
	pitchingAccountStatus?: string;
	pitchingRenewalDate?: string;
	pitchingAppleRenewalDate?: string;
	pitchingHadApplePaymentApplied?: boolean;
	pitchingTrialing?: boolean;
	pitchingActiveMembership?: boolean;
	pitchingSubscribed?: boolean;
	pitchingSubscribedTo?: string;
	axonBaseballId?: string;
	axonSoftballId?: string;
	paidViaLicense?: boolean;
	licenseOwner?: boolean;
	paidLicensesForCurrentBillingCycle?: number;
	appVersionOverrides?: UserAppVersionOverrideDTOV2[];
	state?: string;
	graduationYear?: string;
	position?: string;
}
